### PR TITLE
Only treat Frozen-Flask warnings as errors, not other warnings

### PR DESCRIPTION
**Pull request by hroncok**
If all warnings are treated as errors and some underlying code emits a PendingDeprecationWarning or such, the site is unfreezable. This change makes sure we only treat the warnings emitted by Frozn Flask as errors.

### CODE REVIEW

**Comment by hroncok** [comment]
This blocks https://github.com/pyvec/naucse.python.cz/pull/71

**Comment by encukou** [comment]
Would Frozen-Flask object to having a common superclass for its warnings?

**Comment by hroncok** [comment]
I got that idea yesterday, but forgot to mention that. I'll send a PR / talk to them.

**Comment by hroncok** [comment]
https://github.com/Frozen-Flask/Frozen-Flask/pull/73

**Comment by hroncok** [comment]
Change upstream, new version released. Amended to use that.

**Comment by hroncok** [comment]
Also added a test.

**Comment by encukou** [comment]
Hi,
I won't have time for reviews until Monday at earliest. I hope my reviews
aren't blocking you.

**Comment by hroncok** [comment]
No rush :)

**Pull request merged**
