### PR TITLE
Improved docs

### PR DESCRIPTION
**Pull request by gtg94**

### CODE REVIEW

**Comment by hroncok** [comment]
Reported. What's going on?

**Comment by encukou** [comment]
A botnet attack?
I've reported the other PRs and limited interactions on this repo to existing users.
One reported user and their PR "mysteriously disappeared" from GitHub, maybe others will also be moderated.

**Comment by encukou** [comment]
I've limited interactions to previous committers.

**Comment by encukou** [comment]
OK, apparently it's a [corporate-sponsored human botnet](https://blog.domenic.me/hacktoberfest/). Or [friendly initiative to get people contributing](https://hacktoberfest.digitalocean.com). Take your pick.

**Comment by encukou** [comment]
The one-day interaction limit expired and we promptly got another one, https://github.com/pyvec/elsa/pull/86.
But since yesteday, GitHub added the option to limit interactions for longer than a day, so I enabled it for a month. That should get us through Spamtoberfest.

**Pull request closed without merging**
